import type { ThemePreset } from './types'
import { resolveCSS } from './resolve'

function header(preset: ThemePreset): string {
  return `# Generated by Anti-shadcn Theme Studio — ${preset.name}`
}

function cssBlock(preset: ThemePreset): string {
  return [
    '## CSS Variables',
    '',
    '```css',
    resolveCSS(preset, 'light', 'v3'),
    '',
    '.dark {',
    resolveCSS(preset, 'dark', 'v3').replace(':root {', '').replace(/^\}$/m, '').trimEnd(),
    '}',
    '```',
  ].join('\n')
}

function personalityBlock(preset: ThemePreset): string {
  const { tone, doList, dontList, componentStyle, colorPhilosophy } = preset.aiPersonality

  const doItems = doList.map((item) => `- ${item}`).join('\n')
  const dontItems = dontList.map((item) => `- ${item}`).join('\n')

  return [
    '## Personality',
    '',
    `**Tone:** ${tone}`,
    '',
    `**Component Style:** ${componentStyle}`,
    '',
    `**Color Philosophy:** ${colorPhilosophy}`,
    '',
    '**Do:**',
    doItems,
    '',
    '**Do Not:**',
    dontItems,
  ].join('\n')
}

export function generateCursorRules(preset: ThemePreset): string {
  return [
    header(preset),
    '',
    cssBlock(preset),
    '',
    personalityBlock(preset),
  ].join('\n')
}

export function generateClaudeMd(preset: ThemePreset): string {
  return [
    header(preset),
    '',
    `> Vibe: ${preset.vibe.join(', ')}`,
    `> Tagline: ${preset.tagline}`,
    '',
    cssBlock(preset),
    '',
    personalityBlock(preset),
  ].join('\n')
}
