import * as fs from 'fs'
import * as path from 'path'

const ROOT = path.resolve(__dirname, '..')

function camelToKebab(str: string): string {
  return str.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`)
}

interface CssToken {
  name: string
  value: string
  group: string
}

function parseGlobalsCss(): CssToken[] {
  const content = fs.readFileSync(path.join(ROOT, 'src/app/globals.css'), 'utf-8')

  const rootMatch = content.match(/:root\s*\{([\s\S]*?)\}/)
  if (!rootMatch) return []

  const rootBlock = rootMatch[1]
  const tokens: CssToken[] = []
  let currentGroup = 'Base Colors'

  const lines = rootBlock.split('\n')
  for (const line of lines) {
    const groupMatch = line.match(/\/\*\s*─+\s*([^─]+?)\s*─/)
    if (groupMatch) {
      currentGroup = groupMatch[1].trim()
      continue
    }

    const tokenMatch = line.match(/^\s*--([a-zA-Z0-9-]+):\s*([^;]+);/)
    if (tokenMatch) {
      tokens.push({
        name: tokenMatch[1].trim(),
        value: tokenMatch[2].trim(),
        group: currentGroup,
      })
    }
  }

  return tokens
}

interface TypescriptField {
  camel: string
  kebab: string
}

function parseThemeTokensInterface(): TypescriptField[] {
  const content = fs.readFileSync(path.join(ROOT, 'src/lib/themes/types.ts'), 'utf-8')

  const interfaceMatch = content.match(/interface ThemeTokens\s*\{([\s\S]*?)\}/)
  if (!interfaceMatch) return []

  const fields: TypescriptField[] = []
  const fieldRegex = /^\s+(\w+):\s*string/gm
  let match: RegExpExecArray | null

  while ((match = fieldRegex.exec(interfaceMatch[1])) !== null) {
    const camel = match[1]
    fields.push({ camel, kebab: camelToKebab(camel) })
  }

  return fields
}

type ZincVioletLight = Record<string, string>

function parseZincVioletLight(): ZincVioletLight {
  const content = fs.readFileSync(
    path.join(ROOT, 'src/lib/themes/presets/zinc-violet.ts'),
    'utf-8'
  )

  const lightMatch = content.match(/light:\s*\{([\s\S]*?)\},/)
  if (!lightMatch) return {}

  const result: ZincVioletLight = {}
  const fieldRegex = /(\w+):\s*'([^']+)'/g
  let match: RegExpExecArray | null

  while ((match = fieldRegex.exec(lightMatch[1])) !== null) {
    const camel = match[1]
    result[camelToKebab(camel)] = match[2]
  }

  return result
}

function main(): void {
  const cssTokens = parseGlobalsCss()
  const tsFields = parseThemeTokensInterface()
  const zincLight = parseZincVioletLight()

  const cssTokenMap = new Map<string, CssToken>()
  for (const t of cssTokens) {
    cssTokenMap.set(t.name, t)
  }

  const tsKebabSet = new Set(tsFields.map((f) => f.kebab))

  const sharedTokens = tsFields.filter((f) => cssTokenMap.has(f.kebab))
  const cssOnlyTokens = cssTokens.filter((t) => !tsKebabSet.has(t.name))
  const tsOnlyTokens = tsFields.filter((f) => !cssTokenMap.has(f.kebab))

  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC'

  const lines: string[] = []

  lines.push('# Token Index — Theme Studio')
  lines.push('> AUTO-GENERATED by scripts/generate-token-index.ts — не редактировать вручную.')
  lines.push('> Обновить: npm run docs:tokens')
  lines.push(`> Дата: ${timestamp}`)
  lines.push('')
  lines.push('## Архитектура токенов')
  lines.push('')
  lines.push(
    'ThemeTokens (src/lib/themes/types.ts) — TypeScript-интерфейс, управляется через Token Editor и пресеты. ' +
      'При смене пресета resolve.ts конвертирует camelCase поля в CSS custom properties и инжектирует их в iframe через postMessage. ' +
      'Результат виден в preview iframe как inline styles на :root.'
  )
  lines.push('')
  lines.push(
    'globals.css — стили AppShell (основного приложения). :root блок содержит дефолтные значения токенов (Zinc Violet light). ' +
      'Эти значения применяются до загрузки любого пресета. Файл читается браузером напрямую — не через ThemeTokens.'
  )
  lines.push('')
  lines.push(
    'Sidebar-токены (sidebarBackground, sidebarForeground и др.) существуют в ThemeTokens и пресетах, ' +
      'но отсутствуют в globals.css — они предназначены только для iframe preview, ' +
      'где ComponentGallery рендерит sidebar-компоненты с полным набором токенов.'
  )
  lines.push('')
  lines.push('## ThemeTokens (управляются через Token Editor и пресеты)')
  lines.push('')
  lines.push('| CSS var | TypeScript field | Группа | Default (Zinc Violet light) |')
  lines.push('|---------|-----------------|--------|----------------------------|')

  for (const field of sharedTokens) {
    const cssToken = cssTokenMap.get(field.kebab)!
    const defaultVal = zincLight[field.kebab] ?? cssToken.value
    lines.push(`| --${field.kebab} | ${field.camel} | ${cssToken.group} | ${defaultVal} |`)
  }

  lines.push('')
  lines.push('## Токены только в globals.css (не в ThemeTokens)')
  lines.push('')
  lines.push('| CSS var | Группа | Значение по умолчанию |')
  lines.push('|---------|--------|-----------------------|')

  for (const token of cssOnlyTokens) {
    lines.push(`| --${token.name} | ${token.group} | ${token.value} |`)
  }

  lines.push('')
  lines.push('## Расхождения (в ThemeTokens, но нет в globals.css)')
  lines.push('')
  lines.push(
    'Следующие поля присутствуют в ThemeTokens и пресетах, но отсутствуют как CSS vars в globals.css. ' +
      'Это намеренно: они инжектируются в iframe preview через postMessage, ' +
      'не в AppShell globals.css.'
  )
  lines.push('')

  for (const field of tsOnlyTokens) {
    const defaultVal = zincLight[field.kebab] ?? '—'
    lines.push(`- \`--${field.kebab}\` (\`${field.camel}\`) — default: ${defaultVal}`)
  }

  lines.push('')

  const output = lines.join('\n')
  const outPath = path.join(ROOT, 'docs/TOKEN-INDEX.md')
  fs.writeFileSync(outPath, output, 'utf-8')
  console.log(`[docs:tokens] Generated ${outPath}`)
}

main()
