import * as fs from 'fs'
import * as path from 'path'

const ROOT = path.resolve(__dirname, '..')

interface ComponentInfo {
  name: string
  file: string
  exports: string[]
  specPath: string
  hasSpec: boolean
  specComplete: string
}

function extractExports(content: string): string[] {
  const exports: string[] = []

  const namedRegex = /export\s+(?:const|function|class|interface|type)\s+(\w+)/g
  let match: RegExpExecArray | null
  while ((match = namedRegex.exec(content)) !== null) {
    exports.push(match[1])
  }

  const braceRegex = /export\s+\{([^}]+)\}/g
  while ((match = braceRegex.exec(content)) !== null) {
    const names = match[1].split(',').map((s) => s.trim().split(/\s+as\s+/).pop()!.trim())
    for (const name of names) {
      if (name && !exports.includes(name)) {
        exports.push(name)
      }
    }
  }

  return exports
}

function getSpecComplete(specPath: string): string {
  if (!fs.existsSync(specPath)) return '—'
  const content = fs.readFileSync(specPath, 'utf-8')
  const match = content.match(/\*\*Spec complete:\*\*\s*(YES|NO)/i)
  if (match) return match[1].toUpperCase()
  const match2 = content.match(/Spec complete:\s*(YES|NO)/i)
  if (match2) return match2[1].toUpperCase()
  return '—'
}

function main(): void {
  const uiDir = path.join(ROOT, 'src/components/ui')
  const specsDir = path.join(ROOT, 'docs/specs')

  if (!fs.existsSync(uiDir)) {
    console.error('[docs:components] src/components/ui/ not found')
    process.exit(1)
  }

  const files = fs.readdirSync(uiDir).filter((f) => f.endsWith('.tsx'))

  const components: ComponentInfo[] = files.map((file) => {
    const name = file.replace('.tsx', '')
    const capitalName = name.charAt(0).toUpperCase() + name.slice(1)
    const filePath = path.join(uiDir, file)
    const content = fs.readFileSync(filePath, 'utf-8')
    const exports = extractExports(content)
    const specPath = path.join(specsDir, `${name}-spec.md`)
    const hasSpec = fs.existsSync(specPath)
    const specComplete = getSpecComplete(specPath)

    return {
      name: capitalName,
      file: `src/components/ui/${file}`,
      exports,
      specPath: `docs/specs/${name}-spec.md`,
      hasSpec,
      specComplete,
    }
  })

  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC'

  const lines: string[] = []

  lines.push('# Component Index — Theme Studio')
  lines.push('> AUTO-GENERATED by scripts/generate-component-index.ts — не редактировать вручную.')
  lines.push('> Обновить: npm run docs:components')
  lines.push(`> Дата: ${timestamp}`)
  lines.push('')
  lines.push('## Архитектура компонентов')
  lines.push('')
  lines.push(
    '**ui/ (Production-ready)** — реиспользуемые компоненты, импортировать в любом месте приложения.'
  )
  lines.push(
    '**ComponentGallery (Preview-only)** — компоненты существуют только внутри preview iframe. ' +
      'НЕ импортировать напрямую — используй shadcn/ui или строй с нуля.'
  )
  lines.push('')
  lines.push('## ui/ — Production компоненты')
  lines.push('')
  lines.push('| Компонент | Файл | Экспортирует | Spec | Spec Complete |')
  lines.push('|-----------|------|-------------|------|---------------|')

  for (const comp of components) {
    const specCell = comp.hasSpec ? `docs/specs/${comp.name.toLowerCase()}-spec.md` : '❌ нет spec'
    const exportsCell = comp.exports.join(', ')
    lines.push(
      `| ${comp.name} | ${comp.file} | ${exportsCell} | ${specCell} | ${comp.specComplete} |`
    )
  }

  lines.push('')
  lines.push('## Preview-only (ComponentGallery)')
  lines.push('')
  lines.push(
    '> Компоненты в preview: Checkbox, Switch, Radio, Tabs, Select, Input, Textarea, Badge, Alert,' +
      ' Table, Separator, Avatar, Progress. Все реализованы в ALE-737 как inline в ComponentGallery.tsx.' +
      ' НЕ являются импортируемыми модулями.'
  )
  lines.push('')

  const output = lines.join('\n')
  const outPath = path.join(ROOT, 'docs/COMPONENT-INDEX.md')
  fs.writeFileSync(outPath, output, 'utf-8')
  console.log(`[docs:components] Generated ${outPath}`)
}

main()
