import * as fs from 'fs'
import * as path from 'path'

const ROOT = path.resolve(__dirname, '..')

function camelToKebab(str: string): string {
  return str.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`)
}

interface CssToken {
  name: string
  value: string
  group: string
}

function parseGlobalsCss(): CssToken[] {
  const content = fs.readFileSync(path.join(ROOT, 'src/app/globals.css'), 'utf-8')

  const rootMatch = content.match(/:root\s*\{([\s\S]*?)\}/)
  if (!rootMatch) return []

  const rootBlock = rootMatch[1]
  const tokens: CssToken[] = []
  let currentGroup = 'Base Colors'

  const lines = rootBlock.split('\n')
  for (const line of lines) {
    const groupMatch = line.match(/\/\*\s*─+\s*([^─]+?)\s*─/)
    if (groupMatch) {
      currentGroup = groupMatch[1].trim()
      continue
    }

    const tokenMatch = line.match(/^\s*--([a-zA-Z0-9-]+):\s*([^;]+);/)
    if (tokenMatch) {
      tokens.push({
        name: tokenMatch[1].trim(),
        value: tokenMatch[2].trim(),
        group: currentGroup,
      })
    }
  }

  return tokens
}

interface TypescriptField {
  camel: string
  kebab: string
}

function parseThemeTokensInterface(): TypescriptField[] {
  const content = fs.readFileSync(path.join(ROOT, 'src/lib/themes/types.ts'), 'utf-8')

  const interfaceMatch = content.match(/interface ThemeTokens\s*\{([\s\S]*?)\}/)
  if (!interfaceMatch) return []

  const fields: TypescriptField[] = []
  const fieldRegex = /^\s+(\w+):\s*string/gm
  let match: RegExpExecArray | null

  while ((match = fieldRegex.exec(interfaceMatch[1])) !== null) {
    const camel = match[1]
    fields.push({ camel, kebab: camelToKebab(camel) })
  }

  return fields
}

type ZincVioletLight = Record<string, string>

function parseZincVioletLight(): ZincVioletLight {
  const content = fs.readFileSync(
    path.join(ROOT, 'src/lib/themes/presets/zinc-violet.ts'),
    'utf-8'
  )

  const lightMatch = content.match(/light:\s*\{([\s\S]*?)\},/)
  if (!lightMatch) return {}

  const result: ZincVioletLight = {}
  const fieldRegex = /(\w+):\s*'([^']+)'/g
  let match: RegExpExecArray | null

  while ((match = fieldRegex.exec(lightMatch[1])) !== null) {
    const camel = match[1]
    result[camelToKebab(camel)] = match[2]
  }

  return result
}

function main(): void {
  const cssTokens = parseGlobalsCss()
  const tsFields = parseThemeTokensInterface()
  const zincLight = parseZincVioletLight()

  const cssTokenMap = new Map<string, CssToken>()
  for (const t of cssTokens) {
    cssTokenMap.set(t.name, t)
  }

  const tsKebabSet = new Set(tsFields.map((f) => f.kebab))

  const sharedTokens = tsFields.filter((f) => cssTokenMap.has(f.kebab))
  const cssOnlyTokens = cssTokens.filter((t) => !tsKebabSet.has(t.name))
  const tsOnlyTokens = tsFields.filter((f) => !cssTokenMap.has(f.kebab))

  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC'

  const lines: string[] = []

  lines.push('# Token Index — Theme Studio')
  lines.push('> AUTO-GENERATED by scripts/generate-token-index.ts — do not edit manually.')
  lines.push('> Regenerate: npm run docs:tokens')
  lines.push(`> Date: ${timestamp}`)
  lines.push('')
  lines.push('## Token architecture')
  lines.push('')
  lines.push(
    'ThemeTokens (src/lib/themes/types.ts) — TypeScript interface managed through the Token Editor and presets. ' +
      'When the preset changes, resolve.ts converts camelCase fields into CSS custom properties and injects them into the iframe via postMessage. ' +
      'The result is visible in the preview iframe as inline styles on :root.'
  )
  lines.push('')
  lines.push(
    'globals.css — AppShell styles (the main application). The :root block holds default token values (Zinc Violet light). ' +
      'These values apply before any preset loads. The file is read directly by the browser — not through ThemeTokens.'
  )
  lines.push('')
  lines.push(
    'Sidebar tokens (sidebarBackground, sidebarForeground, etc.) exist in ThemeTokens and presets ' +
      'but are absent from globals.css — they are intended only for the iframe preview, ' +
      'where ComponentGallery renders sidebar components with the full token set.'
  )
  lines.push('')
  lines.push('## ThemeTokens (managed through Token Editor and presets)')
  lines.push('')
  lines.push('| CSS var | TypeScript field | Group | Default (Zinc Violet light) |')
  lines.push('|---------|-----------------|--------|----------------------------|')

  for (const field of sharedTokens) {
    const cssToken = cssTokenMap.get(field.kebab)!
    const defaultVal = zincLight[field.kebab] ?? cssToken.value
    lines.push(`| --${field.kebab} | ${field.camel} | ${cssToken.group} | ${defaultVal} |`)
  }

  lines.push('')
  lines.push('## Tokens only in globals.css (not in ThemeTokens)')
  lines.push('')
  lines.push('| CSS var | Group | Default value |')
  lines.push('|---------|--------|-----------------------|')

  for (const token of cssOnlyTokens) {
    lines.push(`| --${token.name} | ${token.group} | ${token.value} |`)
  }

  lines.push('')
  lines.push('## Discrepancies (in ThemeTokens but absent from globals.css)')
  lines.push('')
  lines.push(
    'The following fields exist in ThemeTokens and presets but are not present as CSS vars in globals.css. ' +
      'This is intentional: they are injected into the iframe preview via postMessage, ' +
      'not into the AppShell globals.css.'
  )
  lines.push('')

  for (const field of tsOnlyTokens) {
    const defaultVal = zincLight[field.kebab] ?? '—'
    lines.push(`- \`--${field.kebab}\` (\`${field.camel}\`) — default: ${defaultVal}`)
  }

  lines.push('')

  const output = lines.join('\n')
  const outPath = path.join(ROOT, 'docs/TOKEN-INDEX.md')
  fs.writeFileSync(outPath, output, 'utf-8')
  console.log(`[docs:tokens] Generated ${outPath}`)
}

main()
