import type { ThemePreset } from '../types'

export const concreteBrutalist: ThemePreset = {
  id: 'concrete-brutalist',
  name: 'Concrete Brutalist',
  tagline: 'Raw structure. No apologies.',
  vibe: ['harsh', 'industrial', 'confrontational'],
  light: {
    background: '5 0% 97%',
    foreground: '0 0% 5%',
    card: '5 0% 94%',
    cardForeground: '0 0% 5%',
    popover: '5 0% 97%',
    popoverForeground: '0 0% 5%',
    primary: '0 0% 5%',
    primaryForeground: '0 0% 100%',
    secondary: '0 0% 92%',
    secondaryForeground: '0 0% 5%',
    muted: '0 0% 88%',
    mutedForeground: '0 0% 40%',
    accent: '45 100% 51%',
    accentForeground: '0 0% 5%',
    destructive: '0 84% 60%',
    destructiveForeground: '0 0% 100%',
    border: '0 0% 20%',
    input: '0 0% 20%',
    ring: '45 100% 51%',
    radius: '0rem',
    chart1: '45 100% 51%',
    chart2: '0 0% 30%',
    chart3: '0 0% 50%',
    chart4: '0 0% 70%',
    chart5: '0 0% 90%',
    sidebarBackground: '5 0% 92%',
    sidebarForeground: '0 0% 5%',
    sidebarPrimary: '0 0% 5%',
    sidebarPrimaryForeground: '0 0% 100%',
    sidebarAccent: '45 100% 51%',
    sidebarAccentForeground: '0 0% 5%',
    sidebarBorder: '0 0% 20%',
    sidebarRing: '45 100% 51%',
  },
  dark: {
    background: '0 0% 8%',
    foreground: '0 0% 95%',
    card: '0 0% 12%',
    cardForeground: '0 0% 95%',
    popover: '0 0% 8%',
    popoverForeground: '0 0% 95%',
    primary: '45 100% 51%',
    primaryForeground: '0 0% 5%',
    secondary: '0 0% 18%',
    secondaryForeground: '0 0% 95%',
    muted: '0 0% 22%',
    mutedForeground: '0 0% 60%',
    accent: '45 100% 51%',
    accentForeground: '0 0% 5%',
    destructive: '0 84% 60%',
    destructiveForeground: '0 0% 100%',
    border: '0 0% 30%',
    input: '0 0% 30%',
    ring: '45 100% 51%',
    radius: '0rem',
    chart1: '45 100% 51%',
    chart2: '0 0% 60%',
    chart3: '0 0% 50%',
    chart4: '0 0% 40%',
    chart5: '0 0% 30%',
    sidebarBackground: '0 0% 11%',
    sidebarForeground: '0 0% 95%',
    sidebarPrimary: '45 100% 51%',
    sidebarPrimaryForeground: '0 0% 5%',
    sidebarAccent: '45 100% 51%',
    sidebarAccentForeground: '0 0% 5%',
    sidebarBorder: '0 0% 30%',
    sidebarRing: '45 100% 51%',
  },
  fonts: {
    heading: "'Arial Black', 'Impact', sans-serif",
    body: "'Courier New', monospace",
    mono: "'Courier New', monospace",
  },
  radius: '0rem',
  shadowStyle: 'none',
  aiPersonality: {
    tone: 'Blunt, direct, zero decoration',
    doList: [
      'Use hard edges and square corners everywhere',
      'Rely on strong typographic hierarchy',
      'Use yellow as the only accent color',
      'Embrace whitespace as negative space, not emptiness',
      'Make borders visible and structural',
    ],
    dontList: [
      'Never round corners',
      'Never use gradients or shadows',
      'Never use more than 3 colors at once',
      'Never write apologetic copy',
      'Never center-align body text',
    ],
    componentStyle: 'Flat, bordered, no-radius cards. Bold uppercase labels. Monospace body text.',
    colorPhilosophy: 'Achromatic base with construction yellow as the sole accent. Color is earned, not decorative.',
  },
}
