import type { ThemePreset } from '../types'

export const concreteBrutalist: ThemePreset = {
  id: 'concrete-brutalist',
  name: 'Concrete Brutalist',
  tagline: 'Raw structure. No apologies.',
  vibe: ['harsh', 'industrial', 'confrontational'],
  light: {
    background: '0 0% 97%',
    foreground: '0 0% 4%',
    card: '0 0% 94%',
    cardForeground: '0 0% 4%',
    popover: '0 0% 97%',
    popoverForeground: '0 0% 4%',
    primary: '0 0% 4%',
    primaryForeground: '0 0% 100%',
    secondary: '0 0% 90%',
    secondaryForeground: '0 0% 4%',
    muted: '0 0% 86%',
    mutedForeground: '0 0% 38%',
    accent: '44 96% 53%',
    accentForeground: '0 0% 4%',
    destructive: '0 84% 55%',
    destructiveForeground: '0 0% 100%',
    border: '0 0% 78%',
    input: '0 0% 78%',
    ring: '44 96% 53%',
    radius: '0rem',
    chart1: '44 96% 53%',
    chart2: '0 0% 30%',
    chart3: '0 0% 50%',
    chart4: '0 0% 65%',
    chart5: '0 0% 82%',
    sidebarBackground: '0 0% 93%',
    sidebarForeground: '0 0% 4%',
    sidebarPrimary: '0 0% 4%',
    sidebarPrimaryForeground: '0 0% 100%',
    sidebarAccent: '44 96% 53%',
    sidebarAccentForeground: '0 0% 4%',
    sidebarBorder: '0 0% 78%',
    sidebarRing: '44 96% 53%',
  },
  dark: {
    background: '0 0% 7%',
    foreground: '0 0% 95%',
    card: '0 0% 11%',
    cardForeground: '0 0% 95%',
    popover: '0 0% 7%',
    popoverForeground: '0 0% 95%',
    primary: '44 96% 53%',
    primaryForeground: '0 0% 4%',
    secondary: '0 0% 17%',
    secondaryForeground: '0 0% 95%',
    muted: '0 0% 20%',
    mutedForeground: '0 0% 58%',
    accent: '44 96% 53%',
    accentForeground: '0 0% 4%',
    destructive: '0 84% 55%',
    destructiveForeground: '0 0% 100%',
    border: '0 0% 25%',
    input: '0 0% 25%',
    ring: '44 96% 53%',
    radius: '0rem',
    chart1: '44 96% 53%',
    chart2: '0 0% 60%',
    chart3: '0 0% 48%',
    chart4: '0 0% 36%',
    chart5: '0 0% 28%',
    sidebarBackground: '0 0% 10%',
    sidebarForeground: '0 0% 95%',
    sidebarPrimary: '44 96% 53%',
    sidebarPrimaryForeground: '0 0% 4%',
    sidebarAccent: '44 96% 53%',
    sidebarAccentForeground: '0 0% 4%',
    sidebarBorder: '0 0% 25%',
    sidebarRing: '44 96% 53%',
  },
  fonts: {
    heading: "var(--font-grotesk), 'Space Grotesk', sans-serif",
    body: "'JetBrains Mono', 'Fira Code', monospace",
    mono: "'JetBrains Mono', 'Fira Code', monospace",
  },
  radius: '0rem',
  shadowStyle: 'none',
  aiPersonality: {
    tone: 'Blunt, direct, zero decoration',
    doList: [
      'Use hard edges and square corners everywhere',
      'Rely on strong typographic hierarchy',
      'Use yellow as the only accent color',
      'Make borders visible and structural',
      'Use negative space deliberately, not as decoration',
    ],
    dontList: [
      'Never round corners',
      'Never use gradients or shadows',
      'Never use more than 3 colors at once',
      'Never write apologetic copy',
      'Never center-align body text',
    ],
    componentStyle:
      'Flat, bordered, zero-radius cards. Bold uppercase labels. Monospace body text.',
    colorPhilosophy:
      'Achromatic base with construction yellow as the sole accent. Color is earned, not decorative.',
  },
}
